services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && cd /myapp && bundle exec rails db:create db:migrate &&bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:6.2
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  rspec:
    build: .
    command: bash -c "bundle exec rails db:create db:schema:load && bundle exec rspec && bundle exec rails db:drop"
    volumes:
      - .:/myapp
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: myapp_test
    profiles:
      - test
volumes:
  postgres_data: